# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comentarios.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63omentarios.proto\"Q\n\x16\x63rearComentarioRequest\x12\x10\n\x08idReceta\x18\x01 \x01(\x05\x12\x11\n\tidUsuario\x18\x02 \x01(\t\x12\x12\n\ncomentario\x18\x03 \x01(\t\"1\n\x19\x65liminarComentarioRequest\x12\x14\n\x0cidComentario\x18\x01 \x01(\x05\"[\n\ncomentario\x12\x14\n\x0cidComentario\x18\x01 \x01(\x05\x12\x10\n\x08idReceta\x18\x02 \x01(\x05\x12\x11\n\tidUsuario\x18\x03 \x01(\t\x12\x12\n\ncomentario\x18\x04 \x01(\t\"\"\n\x10\x63omentarioStatus\x12\x0e\n\x06\x65stado\x18\x01 \x01(\x05\"+\n\x17traerComentariosRequest\x12\x10\n\x08idReceta\x18\x01 \x01(\x05\"<\n\x18traerComentariosResponse\x12 \n\x0b\x63omentarios\x18\x01 \x03(\x0b\x32\x0b.comentario2\xe4\x01\n\x13servicioComentarios\x12=\n\x0f\x63rearComentario\x12\x17.crearComentarioRequest\x1a\x11.comentarioStatus\x12\x43\n\x12\x65liminarComentario\x12\x1a.eliminarComentarioRequest\x1a\x11.comentarioStatus\x12I\n\x12obtenerComentarios\x12\x18.traerComentariosRequest\x1a\x19.traerComentariosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comentarios_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREARCOMENTARIOREQUEST']._serialized_start=21
  _globals['_CREARCOMENTARIOREQUEST']._serialized_end=102
  _globals['_ELIMINARCOMENTARIOREQUEST']._serialized_start=104
  _globals['_ELIMINARCOMENTARIOREQUEST']._serialized_end=153
  _globals['_COMENTARIO']._serialized_start=155
  _globals['_COMENTARIO']._serialized_end=246
  _globals['_COMENTARIOSTATUS']._serialized_start=248
  _globals['_COMENTARIOSTATUS']._serialized_end=282
  _globals['_TRAERCOMENTARIOSREQUEST']._serialized_start=284
  _globals['_TRAERCOMENTARIOSREQUEST']._serialized_end=327
  _globals['_TRAERCOMENTARIOSRESPONSE']._serialized_start=329
  _globals['_TRAERCOMENTARIOSRESPONSE']._serialized_end=389
  _globals['_SERVICIOCOMENTARIOS']._serialized_start=392
  _globals['_SERVICIOCOMENTARIOS']._serialized_end=620
# @@protoc_insertion_point(module_scope)
