# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: receta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creceta.proto\"D\n\x06receta\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x0c\n\x04\x66oto\x18\x02 \x01(\t\x12\r\n\x05tpMin\x18\x03 \x01(\t\x12\r\n\x05tpMax\x18\x04 \x01(\t\"U\n\x16traerRecetasPorRequest\x12\x17\n\x0ftiempoEnMinutos\x18\x01 \x01(\t\x12\x11\n\tcategoria\x18\x02 \x01(\t\x12\x0f\n\x07\x63reador\x18\x03 \x01(\t\"3\n\x17traerRecetasPorResponse\x12\x18\n\x07recetas\x18\x01 \x03(\x0b\x32\x07.receta2V\n\x0eservicioReceta\x12\x44\n\x0ftraerRecetasPor\x12\x17.traerRecetasPorRequest\x1a\x18.traerRecetasPorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'receta_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RECETA']._serialized_start=16
  _globals['_RECETA']._serialized_end=84
  _globals['_TRAERRECETASPORREQUEST']._serialized_start=86
  _globals['_TRAERRECETASPORREQUEST']._serialized_end=171
  _globals['_TRAERRECETASPORRESPONSE']._serialized_start=173
  _globals['_TRAERRECETASPORRESPONSE']._serialized_end=224
  _globals['_SERVICIORECETA']._serialized_start=226
  _globals['_SERVICIORECETA']._serialized_end=312
# @@protoc_insertion_point(module_scope)
