-- MySQL Script generated by MySQL Workbench
-- Wed Sep 27 15:35:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdrecetas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdrecetas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdrecetas` DEFAULT CHARACTER SET utf8 ;
USE `bdrecetas` ;

-- -----------------------------------------------------
-- Table `bdrecetas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`usuario` (
  `usuario` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `popularidad` INT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdrecetas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`categoria` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdrecetas`.`receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`receta` (
  `idReceta` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(256) NULL,
  `foto1` VARCHAR(1600) NULL,
  `foto2` VARCHAR(1600) NULL,
  `foto3` VARCHAR(1600) NULL,
  `foto4` VARCHAR(1600) NULL,
  `foto5` VARCHAR(1600) NULL,
  `pasos` VARCHAR(1600) NULL,
  `tiempoEnMinutos` INT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `creador` VARCHAR(25) NOT NULL,
  `popularidad` INT NULL,
  `ingredientes` VARCHAR(1600) NULL,
  PRIMARY KEY (`idReceta`),
  INDEX `fk_Receta_Categoria1_idx` (`categoria` ASC) VISIBLE,
  INDEX `fk_Receta_Usuario1_idx` (`creador` ASC) VISIBLE,
  CONSTRAINT `fk_Receta_Categoria1`
    FOREIGN KEY (`categoria`)
    REFERENCES `bdrecetas`.`categoria` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receta_Usuario1`
    FOREIGN KEY (`creador`)
    REFERENCES `bdrecetas`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdrecetas`.`ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`ingrediente` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdrecetas`.`receta_has_ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`receta_has_ingrediente` (
  `idReceta` INT NOT NULL,
  `ingrediente` VARCHAR(45) NOT NULL,
  `cantidad` INT NULL,
  `tipoDeMedida` VARCHAR(45) NULL,
  PRIMARY KEY (`idReceta`, `ingrediente`),
  INDEX `fk_Receta_has_Ingrediente_Ingrediente1_idx` (`ingrediente` ASC) VISIBLE,
  INDEX `fk_Receta_has_Ingrediente_Receta_idx` (`idReceta` ASC) VISIBLE,
  CONSTRAINT `fk_Receta_has_Ingrediente_Receta`
    FOREIGN KEY (`idReceta`)
    REFERENCES `bdrecetas`.`receta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receta_has_Ingrediente_Ingrediente1`
    FOREIGN KEY (`ingrediente`)
    REFERENCES `bdrecetas`.`ingrediente` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdrecetas`.`siguiendo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`siguiendo` (`Usuario_Seguidor` VARCHAR(25) NOT NULL, `Usuario_Seguido` VARCHAR(25) NOT NULL, PRIMARY KEY (`Usuario_Seguidor`, `Usuario_Seguido`));
-- -----------------------------------------------------
-- Table `bdrecetas`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`comentarios` (`idComentario` INT NOT NULL AUTO_INCREMENT, `idReceta` INT NOT NULL, `idUsuario` VARCHAR(25) NOT NULL, `comentario` VARCHAR(255) NOT NULL, PRIMARY KEY (`idComentario`));


-- -----------------------------------------------------
-- Table `bdrecetas`.`receta_favorita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`receta_favorita` (
  `usuario` VARCHAR(25) NOT NULL,
  `idReceta` INT NOT NULL,
  PRIMARY KEY (`usuario`, `idReceta`),
  INDEX `fk_Usuario_has_Receta_Receta1_idx` (`idReceta` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Receta_Usuario1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Receta_Usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `bdrecetas`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Receta_Receta1`
    FOREIGN KEY (`idReceta`)
    REFERENCES `bdrecetas`.`receta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdrecetas`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(256) NULL,
  `idReceta` INT NOT NULL,
  `usuario` VARCHAR(25) NOT NULL,
  `respondeA` INT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_Comentario_Receta1_idx` (`idReceta` ASC) VISIBLE,
  INDEX `fk_Comentario_Usuario1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_Comentario_Comentario1_idx` (`respondeA` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_Receta1`
    FOREIGN KEY (`idReceta`)
    REFERENCES `bdrecetas`.`receta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `bdrecetas`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Comentario1`
    FOREIGN KEY (`respondeA`)
    REFERENCES `bdrecetas`.`comentario` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdrecetas`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdrecetas`.`calificacion` (
  `usuario` VARCHAR(25) NOT NULL,
  `idReceta` INT NOT NULL,
  `calificacion` INT NULL,
  PRIMARY KEY (`usuario`, `idReceta`),
  INDEX `fk_Usuario_has_Receta_Receta2_idx` (`idReceta` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Receta_Usuario2_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Receta_Usuario2`
    FOREIGN KEY (`usuario`)
    REFERENCES `bdrecetas`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Receta_Receta2`
    FOREIGN KEY (`idReceta`)
    REFERENCES `bdrecetas`.`receta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `bdrecetas`.`usuario` (`usuario`, `email`, `nombre`, `password`, `tipo`) VALUES ('admin', 'admin@admin.com', 'admin', 'admin', 'admin');
INSERT INTO `bdrecetas`.`usuario` (`usuario`, `email`, `nombre`, `password`, `tipo`) VALUES ('roberto', 'roberto@roberto.com', 'roberto', 'roberto', 'roberto');

INSERT INTO `bdrecetas`.`categoria` (`nombre`) VALUES ('Desayuno');
INSERT INTO `bdrecetas`.`categoria` (`nombre`) VALUES ('Almuerzo');
INSERT INTO `bdrecetas`.`categoria` (`nombre`) VALUES ('Cena');
INSERT INTO `bdrecetas`.`categoria` (`nombre`) VALUES ('Todas');

INSERT INTO `bdrecetas`.`receta` (`titulo`, `descripcion`, `foto1`, `foto2`, `foto3`, `foto4`, `foto5`, `pasos`, `tiempoEnMinutos`, `categoria`, `creador`,`ingredientes`) VALUES ('Huevos con jamon', 'Huevos con jamon', 'https://cdn0.recetasgratis.net/es/posts/2/9/7/huevos_con_jamon_y_frijoles_76792_orig.jpg', NULL, NULL, NULL, NULL, '1. Cocinar los huevos en una sarten\n2. Cocinar el jamon en otra sarten\n3. Servir en un plato', '10', 'Desayuno', 'admin','Huevos, jamon, sal, pimienta, aceite de oliva');

INSERT INTO `bdrecetas`.`receta` (`titulo`, `descripcion`, `foto1`, `foto2`, `foto3`, `foto4`, `foto5`, `pasos`, `tiempoEnMinutos`, `categoria`, `creador`,`ingredientes`) VALUES ('Frijoles', 'Frijoles muy ricos con salsa especial', 'https://www.goya.com/media/4156/colombian-beans.jpg?quality=80', NULL, NULL, NULL, NULL, '1. Servir 2. Poner salsa', '10', 'Almuerzo', 'roberto','Frijoles, salsa pomarolla, sal, pimienta, aceite de oliva');